# move app.json and mapbox.json to /app/public/js before executing

# building
FROM node:lts-alpine as build
RUN apk add git
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --legacy-peer-deps
RUN npm install cross-env -g
RUN npm install react-scripts -g
COPY ./app ./
RUN cp -r /app/public/ /app/node_modules/static-content/
RUN npm run build-app-dev

# containerizing
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx/app.dev.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]